/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.assignment.bank;

import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Alekla
 */
public class Record_Panel extends javax.swing.JFrame
{

    /**
     * Creates new form Option_Panel
     */
    void set_date()
    {
        Main_Driver.date_srt = "" + from_YYYY.getText() + "-" + from_MM.getText() + "-" + from_DD.getText() + " 00:00:00";
        Main_Driver.date_end = "" + to_YYYY.getText() + "-" + to_MM.getText() + "-" + to_DD.getText() + " 23:59:59";
    }

    void lock_panel()
    {
        from_YYYY.setEnabled(false);
        from_MM.setEnabled(false);
        from_DD.setEnabled(false);
        to_YYYY.setEnabled(false);
        to_MM.setEnabled(false);
        to_DD.setEnabled(false);
    }

    public Record_Panel()
    {
        initComponents();
        rec_disp.setText("<html><p style=\"text-align:center;\"> PORFAVOR INTRODUZCA LA FECHA INICIAL <br><br> LA FECHA FINAL Y <br><br> LA DIRECCIÓN DE CORREO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        rec_panel = new javax.swing.JPanel();
        from_label = new javax.swing.JLabel();
        from_DD = new javax.swing.JTextField();
        end_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        from_MM = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        from_YYYY = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        to_DD = new javax.swing.JTextField();
        to_MM = new javax.swing.JTextField();
        to_YYYY = new javax.swing.JTextField();
        email_add = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        back_btnActionPerformed = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cancel_btnActionPerformed = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        rec_disp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(480, 640));
        setResizable(false);

        from_label.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        from_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        from_label.setText("Fecha de inicio");

        from_DD.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        from_DD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        from_DD.setText("DD");

        end_label.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        end_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        end_label.setText("Fecha del fin");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setText("/");

        from_MM.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        from_MM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        from_MM.setText("MM");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel2.setText("/");

        from_YYYY.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        from_YYYY.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        from_YYYY.setText("YYYY");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel3.setText("/");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel4.setText("/");

        to_DD.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        to_DD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        to_DD.setText("DD");

        to_MM.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        to_MM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        to_MM.setText("MM");

        to_YYYY.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        to_YYYY.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        to_YYYY.setText("YYYY");

        email_add.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        email_add.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email_add.setText("Dirección de correo");
        email_add.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                email_addActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 204, 0));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ENVIAR INFORMACIÓN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(103, 103, 103))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        back_btnActionPerformed.setBackground(new java.awt.Color(51, 153, 255));

        jLabel6.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ATRAS");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout back_btnActionPerformedLayout = new javax.swing.GroupLayout(back_btnActionPerformed);
        back_btnActionPerformed.setLayout(back_btnActionPerformedLayout);
        back_btnActionPerformedLayout.setHorizontalGroup(
            back_btnActionPerformedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(back_btnActionPerformedLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel6)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        back_btnActionPerformedLayout.setVerticalGroup(
            back_btnActionPerformedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cancel_btnActionPerformed.setBackground(new java.awt.Color(255, 51, 51));
        cancel_btnActionPerformed.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                cancel_btnActionPerformedMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CANCELAR");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout cancel_btnActionPerformedLayout = new javax.swing.GroupLayout(cancel_btnActionPerformed);
        cancel_btnActionPerformed.setLayout(cancel_btnActionPerformedLayout);
        cancel_btnActionPerformedLayout.setHorizontalGroup(
            cancel_btnActionPerformedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancel_btnActionPerformedLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel7)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        cancel_btnActionPerformedLayout.setVerticalGroup(
            cancel_btnActionPerformedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout rec_panelLayout = new javax.swing.GroupLayout(rec_panel);
        rec_panel.setLayout(rec_panelLayout);
        rec_panelLayout.setHorizontalGroup(
            rec_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rec_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rec_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rec_panelLayout.createSequentialGroup()
                        .addGroup(rec_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(rec_panelLayout.createSequentialGroup()
                                .addComponent(from_DD, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(from_MM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(from_YYYY, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(from_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(rec_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(rec_panelLayout.createSequentialGroup()
                                .addComponent(to_DD, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(to_MM, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(to_YYYY, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(end_label, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(email_add, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(rec_panelLayout.createSequentialGroup()
                        .addComponent(back_btnActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancel_btnActionPerformed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        rec_panelLayout.setVerticalGroup(
            rec_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rec_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rec_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rec_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(from_DD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(from_MM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(from_YYYY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rec_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(rec_panelLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(rec_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(to_DD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(to_MM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(to_YYYY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(end_label)
                        .addComponent(from_label)))
                .addGap(22, 22, 22)
                .addComponent(email_add, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(rec_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cancel_btnActionPerformed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(back_btnActionPerformed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        rec_disp.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        rec_disp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rec_disp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/assignment/bank/images/panel_screen.png"))); // NOI18N
        rec_disp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rec_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rec_disp, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(rec_disp, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(rec_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void email_addActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_email_addActionPerformed
    {//GEN-HEADEREND:event_email_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_addActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel1MouseClicked
    {//GEN-HEADEREND:event_jPanel1MouseClicked
        set_date();
        try
        {
            String email = email_add.getText();
            rec_disp.setText("<html><p style=\"text-align:center;\"> >>> ENVIANDO CORREO >>>");
            Main_Driver.bank_pros.getTransactions(Main_Driver.acc_num, Main_Driver.date_srt, Main_Driver.date_end, email);
            rec_disp.setText("<html><p style=\"text-align:center;\"> CORREO ENVIADO ");

        }
        catch (RemoteException ex)
        {
            Logger.getLogger(Record_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabel6MouseClicked
    {//GEN-HEADEREND:event_jLabel6MouseClicked
        new Menu_Panel().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabel7MouseClicked
    {//GEN-HEADEREND:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void cancel_btnActionPerformedMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_cancel_btnActionPerformedMouseClicked
    {//GEN-HEADEREND:event_cancel_btnActionPerformedMouseClicked
        new Home_Panel().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancel_btnActionPerformedMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Record_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Record_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Record_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Record_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
        {
            new Record_Panel().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel back_btnActionPerformed;
    private javax.swing.JPanel cancel_btnActionPerformed;
    private javax.swing.JTextField email_add;
    private javax.swing.JLabel end_label;
    private javax.swing.JTextField from_DD;
    private javax.swing.JTextField from_MM;
    private javax.swing.JTextField from_YYYY;
    private javax.swing.JLabel from_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel rec_disp;
    private javax.swing.JPanel rec_panel;
    private javax.swing.JTextField to_DD;
    private javax.swing.JTextField to_MM;
    private javax.swing.JTextField to_YYYY;
    // End of variables declaration//GEN-END:variables
}
